version: "3.8"

services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql:8.0.27
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: victim
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: my_db
    ports:
        - "3306:3306"


  java-springboot-app:
    container_name: java-springboot-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    restart: on-failure
    ports:
      - "9800:9800"





